development:
  GMAIL_USERNAME: me2mailer@gmail.com
  GMAIL_PASSWORD: 1987x1t9

test:
  GMAIL_USERNAME: me2mailer@gmail.com
  GMAIL_PASSWORD: 1987x1t9

production:
  GMAIL_USERNAME: me2mailer@gmail.com
  GMAIL_PASSWORD: 1987x1t9