development:
  GMAIL_USERNAME: me2mailer@gmail.com
  GMAIL_PASSWORD: abcd-1234

test:
  GMAIL_USERNAME: me2mailer@gmail.com
  GMAIL_PASSWORD: abcd-1234

production:
  GMAIL_USERNAME: me2mailer@gmail.com
  GMAIL_PASSWORD: abcd-1234